### ISSUE TITLE
May I ask a few questions?

### ISSUE THREAD

**Issue by kadaInC** [fingerprintjs/fingerprint-android#34]
Sorry I'm new, wanna know is there any docs to descript the v1, v2 , v3 ?
As I want to know what is the different of them, and what is stable, optimal , unique device fingerprint
thank you for your help

**Comment by Alexey-Verkhovsky** [comment]
Hi! 

The main purpose of fingerprinting – is an additional way for identification that is harder to spoof/fake.
So `STABLE`, `UNIQUE`, and `OPTIMAL` – are the three additional IDs.
`STABLE` is calculated using stable hardware signals, and it's not changing after factory reset. You also should keep in mind that this means that a lot of devices (with the same hardware) will have the same ID. You can consider this STABLE fingerprint as a hardware ID.
`UNIQUE`, on the opposite, is calculated using a big amount of signals. By design UNIQUE fingerprint with a very high probability matches only one user. But it has a downside: it is not stable, the fingerprint changes when some device settings/applications change.
So `OPTIMAL` - it is somewhere in the between. It is more stable than the UNIQUE fingerprint and more unique than the STABLE fingerprint.

v1, v2, v3 are versions of these fingerprints, use the latest if you haven't used any of them.
In the future, there will be improvements of fingerprint stability and uniqueness, and to not break existing usage of fingerprint version should be set explicitly.

Feel free to ask anything!
